version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/calculatorPG
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv calculator
            . calculator/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . calculator/bin/activate
            flake8 --exclude=venv* --statistics
            pytest tests -v --cov=calculator
workflows:
  version: 2
  build_and_test:
    jobs:
      - build