version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.13.2

    working_directory: ~/calculatorPG 

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv calculator
            . calculator/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . calculator/bin/activate
            flake8 --exclude=venv* --statistics
            pytest tests -v --cov=calculator
workflows:
  version: 2
  build_and_test:
    jobs:
      - build